#!/bin/bash

if [ -e /sys/class/hwmon/hwmon0/temp1_input ]; then
  HWPATH=/sys/class/hwmon/hwmon0
else
  HWPATH=/sys/class/hwmon/hwmon0/device
fi

HTEMP[0]="CPU_00|+$(( $(cat ${HWPATH}/temp1_input)/1000 )).0°C"
HTEMP[1]="CPU_01|+$(( $(cat ${HWPATH}/temp1_input)/1000 )).0°C"
#HTEMP[0]="CPU_00|$(sensors | sed -rn 's|^Core\s+0:\s+(\S+)\s+.*$|\1|p')"
#HTEMP[1]="CPU_01|$(sensors | sed -rn 's|^Core\s+1:\s+(\S+)\s+.*$|\1|p')"

HWPATH=/sys/class/hwmon/hwmon1/device

HTEMP[2]="MBR_t1|+$(( $(cat ${HWPATH}/temp1_input)/1000 )).0°C"
HTEMP[3]="MBR_t2|+$(( $(cat ${HWPATH}/temp2_input)/1000 )).0°C"
HTEMP[4]="MBR_t3|+$(( $(cat ${HWPATH}/temp3_input)/1000 )).0°C"

HTEMP[5]="GPU_nv|+$(nvidia-smi --format='csv,noheader' --query-gpu='temperature.gpu').0°C"

for d in "${HTEMP[@]}"; do echo "$d"; done

